version: "3"
services: #services means the docker containers
  dockernodeapp:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      # - ./:/app
      - dockernodeappDevNodeModules:/app/node_modules
    command: npm run dev
volumes:
  dockernodeappDevNodeModules:
