version: "3"
services: #services means the docker containers
  dockernodeapp:
    volumes:
      - ./:/app
      - dockernodeappDevNodeModules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
volumes:
  dockernodeappDevNodeModules:
