version: "3"
services: #services means the docker containers
  dockernodeapp:
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: node index.js
