version: "3"
services: #services means the docker containers
  dockernodeapp:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    # environment: # you can seperately specify environment variables here
    #   - PORT=3000
    env_file:
      - ./.env
